### PR TITLE
try to add br_table detail

### PR DESCRIPTION
**Pull request by SpikeI**
Try to add brtable detail in disasm. I use malloc to get dynamic memory cost, but can't find a way to free it.

### CODE REVIEW

**Comment by aquynh** [comment]
sounds like we need to extend `cs_free()` with a `csh` handle to free this brtable.

**Comment by SpikeI** [comment]
> sounds like we need to extend `cs_free()` with a `csh` handle to free this brtable.

If we free it in cs_close(), we should get memory pointer from cs_struct?

**Comment by aquynh** [comment]
No, we need to free memory of instructions (generated by cs_disasm()), but
not to close engine (with cs_close())

**Comment by Rot127** [comment]
Thank you for the PR! I closed it because it is out of date. With the new [auto-sync update for v6](https://github.com/capstone-engine/capstone/blob/next/docs/cs_v6_release_guide.md) we made many changes to some main architectures and will do also to others.
This also changed the requirements we have now for new PRs.
 
If you still want to merge the changes, please rebase your fix onto the newest `next` branch and open a new PR.

**Pull request closed without merging**
