### PR TITLE
Make it pickable

### PR DESCRIPTION
**Pull request by feliam**

### CODE REVIEW

**Comment by aquynh** [comment]
this is interesting! can you confirm that Cython still works?

**Comment by danghvu** [comment]
I worry this will break in the future if there are hidden states in the capstone context (currently or in the future).

If serialization is required, I suggest having a separate interface/method to convert instructions to static python object such as tuple/dict.

**Comment by feliam** [comment]
danghvu I fear the same thing. 
Although most of the data needed to recreate the state is saved. (Notably not the skipdata thing).
Having a static python object for all things would be great but it's a lot of work for all the archs.

Can you thing of an example of hidden state? Or can you take a quick look to see if I'm missing something important?

**Comment by danghvu** [comment]
> Having a static python object for all things would be great but it's a lot of work for all the archs.

What I meant was you can return the state object (created inside `__set_state__` to the user so they can perform pickle over it instead of trying to pickle `_cs_insn` or `Cs` object. 

Actually I think you made a great care, I am only not sure if this is generic enough.

**Comment by XVilka** [comment]
Since there were no updates and further interest - maybe it is better to close this?

**Comment by deco-dev** [comment]
I need the this patch. I encountered pickle error.
```
ValueError: ctypes objects containing pointers cannot be pickled
```

**Comment by Rot127** [comment]
Thank you for the PR! I closed it because it is out of date. With the new [auto-sync update for v6](https://github.com/capstone-engine/capstone/blob/next/docs/cs_v6_release_guide.md) we made many changes to some main architectures and will do also to others.
This also changed the requirements we have now for new PRs.
 
If you still want to merge the changes, please rebase your fix onto the newest `next` branch and open a new PR.

**Pull request closed without merging**
