### PR TITLE
support disassembling bytes from memoryview

### PR DESCRIPTION
**Pull request by huettenhain**
Recreation of https://github.com/aquynh/capstone/pull/1758 relative to the `next` branch.

### CODE REVIEW

**Comment by kabeor** [comment]
could you provide a testcase for this？

**Comment by kabeor** [comment]
@huettenhain I tried to verify this PR with following script

(a part of test_basic.py)
```python
            md = Cs(arch, mode)
            code = memoryview(code)  # added this to check if memoryview work

            if syntax is not None:
                md.syntax = syntax

            for insn in md.disasm(code, 0x1000):
                print("0x%x:\t%s\t%s" % (insn.address, insn.mnemonic, insn.op_str))
```

but get this issue

```
File "capstone\bindings\python\capstone\__init__.py", line 1103, in disasm
    code = ctypes.byref(ctypes.c_char.from_buffer(code))
TypeError: underlying buffer is not writable
```

I think you should fix the compatibility of memoryview and ctypes

**Comment by huettenhain** [comment]
Hey! Sorry for the delay. Indeed I was not aware that ctypes would require the buffer to be writable. I think it might be best to simply include this as a check, I'll update the PR soon.

**Comment by huettenhain** [comment]
Hey @kabeor I didn't manage to build this locally, otherwise I would have tested it myself. I updated the PR so that it should work on any writable buffer type, including `bytearray` and `memoryview`.

**Comment by kabeor** [comment]
@huettenhain I tried to write a test case to verify your PR, but it didn't work. Can you write a test case function in bindings/python/test_basic.py?

**Comment by huettenhain** [comment]
I added a test and fixed one remaining bug in the code.

**Comment by kabeor** [comment]
Test confirmed. Thanks for your contribution.

**Pull request merged**
