### PR TITLE
fixed library extension to build properly under CYGWIN

### PR DESCRIPTION
**Pull request by Smartsmurf**
Currently capstone fails to build under CYGWIN although it seems supported.

Please find attached the pull request to fix that (instead of "capstone." it now uses "capstone.lib" / "capstone.dll").

### CODE REVIEW

**Comment by kabeor** [comment]
@Smartsmurf thanks for PR, looks like CIFuzz is failed, can you fix this? and plz rebase to dev branch

**Comment by kabeor** [comment]
Don't forget to rebase to dev branch, thank you

**Comment by Smartsmurf** [comment]
@kabeor fixed CIFuzz and rebased against master branch.

**Comment by kabeor** [comment]
> @kabeor fixed CIFuzz and rebased against master branch.

capstone-engine only accept PR for dev branch, now you are in master branch, change it to dev plz.
we will merge dev to master when ready to release a new version

**Comment by Smartsmurf** [comment]
OK, what is dev branch? the one named "next"?

**Comment by kabeor** [comment]
oh, my fault, yes, 'next' branch

**Comment by kabeor** [comment]
move to #1791, close this pr

**Pull request closed without merging**
