### PR TITLE
Add Renesas SuperH instructions support

### PR DESCRIPTION
**Pull request by ysat0**
This changes added Renesas SuperH CPUs instruction support.

### CODE REVIEW

**Comment by aquynh** [comment]
nice, please add a sample test under tests/ directory for your arch.

is this coming from LLVM? if so, please put the version information somewhere under arch/SH.

**Comment by aquynh** [comment]
sh.h is missing.

please fix the CI.

**Comment by ysat0** [comment]
Sorry. I overlooked your comment.
This change is not related to LLVM.
Added missing files. It should now build.

**Comment by aquynh** [comment]
Please add tests/test_sh.c

**Comment by ysat0** [comment]
This is it.
commit fb25d7fcbffb2b696df7418e1f1fe366801af74c
Author: Yoshinori Sato <ysato@users.sourceforge.jp>
Date:   Wed Oct 12 20:02:14 2022 +0900

    sh: testcase
    
    Signed-off-by: Yoshinori Sato <ysato@users.sourceforge.jp>

**Comment by DMaroo** [comment]
Can this be merged? It'd be nice to have SuperH disassembly support in Capstone. [Rizin](https://github.com/rizinorg/rizin) has it's own makeshift disassembler, but it'd be nice for us to use this one, since we already use Capstone for disassembling other architectures.

**Comment by aquynh** [comment]
sorry for delay, i will have a quick review this week.

**Comment by DMaroo** [comment]
Any updates on this?

**Review by kabeor — APPROVED** [review]
This looks good for me. Any question? @aquynh Or I'll merge it this week.

**Comment by XVilka** [comment]
@kabeor have you had a time to check this?

**Comment by kabeor** [comment]
Happy Chinese New Year！Thanks for your contribution. Merged.

**Comment by ysat0** [comment]
Thanks.

**Pull request merged**
