### PR TITLE
Fix access bug for TEST op

### PR DESCRIPTION
**Pull request by melynx**
Results for TEST instructions are discarded hence operands should have
no write access.

### CODE REVIEW

**Comment by aquynh** [comment]
can you also fix `X86MappingInsnOp_reduce.inc` at the same time?

**Comment by melynx** [comment]
done :)

**Comment by aquynh** [comment]
looking at those TEST variants in the same file, the access info is still wrong, such as `X86_TEST8mi_alt`, etc. can you fix them too?

**Comment by melynx** [comment]
what do the alt variants actually mean?

**Comment by aquynh** [comment]
> what do the alt variants actually mean?

for example X86_TEST8mi_alt.

please review all TEST opcodes, too.

**Comment by aquynh** [comment]
merged, thanks!

**Pull request merged**
