### PR TITLE
Add aarch64 wheel build support

### PR DESCRIPTION
**Pull request by odidev**
Added aarch64 wheel build support.
Related to https://github.com/aquynh/capstone/issues/1768, @veritas501 Could you please review this PR?

### CODE REVIEW

**Comment by chfl4gs** [comment]
Please take at look @ `dockcross/manylinux2014-aarch64` docker build image [dockcross](https://github.com/dockcross/dockcross) 

And spin off a matrix for aarch64 build, I think that will save you time in installing build toolchains.

**Review by chfl4gs — COMMENTED** [review]
Please take at look @ `dockcross/manylinux2014-aarch64` docker build image [dockcross](https://github.com/dockcross/dockcross).

And spin off a matrix for aarch64 build, I think that will save you time in installing build toolchains.

**Comment by odidev** [comment]
I built the aarch64 wheel with the `dockcross/manylinux2014-aarch64` image. Although the artifacts are built for aarch64, the wheel name shows `capstone-5.0.0-py2.py3-none-manylinux2014_x86_64.whl`. 
Could you please share your opinion on whether to rename the wheel name or build wheels with manylinux containers?

**Comment by aquynh** [comment]
@chfl4gs please can you ack this?

**Comment by odidev** [comment]
@chfl4gs, Could you please have a look at this?

**Comment by flit** [comment]
Imo, you should be using [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) for building wheels. It can completely automate building wheels for many architectures, including aarch64, on macOS, Linux, and Windows. And it's supported by the PyPA so is regularly updated.

I may create a PR to switch capstone to using cibuildwheel, as I'd like macOS wheels…

**Comment by XVilka** [comment]
@flit 

> I may create a PR to switch capstone to using cibuildwheel, as I'd like macOS wheels…

It's a good time to do that since capstone is about to release 5.0

**Comment by kabeor** [comment]
More kind of wheel supports has been adding in #2099. Thanks again for your contribution. Closed.

**Pull request closed without merging**
