### PR TITLE
Autosync -  Refreshed

### PR DESCRIPTION
**Pull request by FlyGoat**
This work is based on #1803.

Note that only MIPS is included in this PR. As that's the arch which I most familiar.

I'll work on RISC-V, sparc and others after got this portion merged.

### CODE REVIEW

**Comment by kabeor** [comment]
@FlyGoat I will create a new branch for this feature tomorrow and plz rebase after that

**Comment by XVilka** [comment]
Were there any changes required on the TableGen backend side? 
- https://github.com/rizinorg/llvm-capstone/tree/auto-sync-update/llvm/utils/TableGen/Capstone

Since this code is autogenerated, I suspect it might

**Comment by kabeor** [comment]
plz rebase to https://github.com/capstone-engine/capstone/tree/autosync branch

**Comment by FlyGoat** [comment]
> plz rebase to https://github.com/capstone-engine/capstone/tree/autosync branch

Done

> Were there any changes required on the TableGen backend side?

No actually I started with files generated by  Phosphorus15.

**Comment by FlyGoat** [comment]
Any update?

**Comment by kabeor** [comment]
@FlyGoat hi,as I mentioned in https://github.com/capstone-engine/capstone/pull/1803#issuecomment-1019642411, plz "do not add any .inc file in this PR, we should PR that alone". 
Besides plz create a new pr to rebase llvm to released version first, then merge this pr.

**Comment by kabeor** [comment]
I think it's better if we can auto generate .inc files and releasing by github action

**Comment by XVilka** [comment]
@FlyGoat how is it going? Do you need any help?

**Comment by FlyGoat** [comment]
Ah my fault, I thought I had updated PR but actually not. Will push tomorrow.

Sorry.

**Comment by FlyGoat** [comment]
@kabeor sorry for the latency, PR sent on llvm-capstone repo.

**Comment by XVilka** [comment]
@FlyGoat I think then splitting the change in two commits - one without autogenerated files that breaks the build and the second with updated autogenerated files that fix the build. @kabeor what do you think about this approach? It will make the review easier as well.

**Comment by kabeor** [comment]
@XVilka yeah，agree with that

**Comment by XVilka** [comment]
@FlyGoat how is it going?

**Comment by Rot127** [comment]
Just as notification: https://github.com/capstone-engine/capstone/pull/1803#issuecomment-1208431338

**Comment by XVilka** [comment]
Probably could be closed in favor of https://github.com/capstone-engine/capstone/pull/1949 
@kabeor

**Pull request closed without merging**
