### PR TITLE
Add support for branch relative group in more architectures

### PR DESCRIPTION
**Pull request by abeaumont**
Follow-up work on #964. Added support for:
* ppc
* sparc
* systemz

### CODE REVIEW

**Comment by aquynh** [comment]
nice work, i suppose you had to look up all the instructions in the CPU manuals of these architectures?

**Comment by abeaumont** [comment]
@aquynh that's correct. I hope I got them right, but if you find anything incorrect please let me know.

**Comment by waywardmonkeys** [comment]
Any chance that this could land on `master`?

**Comment by waywardmonkeys** [comment]
@aquynh Ping on this one too?

**Comment by pranith** [comment]
Can you please generate a new PR on [libcapstone](https://github.com/libcapstone/libcapstone)?

**Comment by XVilka** [comment]
Likely not necessary anymore with auto-sync work being done for PPC cc @Rot127

**Comment by Rot127** [comment]
`PPC` has this information with `auto-sync`. Haven't checked the other archs. But the `branch_relative` flag is pretty much always present.

**Comment by Rot127** [comment]
Close it because auto-sync introduced the feature.

**Pull request closed without merging**
