### PR TITLE
Fix PPC insn names and psq displacement

### PR DESCRIPTION
**Pull request by terorie**
Fixes bug where PowerPC `psq_l`, `psq_lu`, `psq_st`, `psq_stu` operands get printed as unsigned operands (should be signed).

Fixes bug where almost all instruction names are wrong in PowerPC due to `PPCMappingInsnName.c` table getting out of sync with `ppc.h`.

Adds ppc32ps and ppc32beps cstool modes.

Avoid setting PowerPC branch hint on signed disp.

--------

Before:

```
% ./cstool/cstool -d --help ppc32beps 'f3ec0ff8'
 0  f3 ec 0f f8  psq_st f31, 0xff8(r12), 0, 0
        ID: 1694 (xvtstdcdp)
        op_count: 4
                operands[0].type: REG = f31
                operands[1].type: MEM
                        operands[1].mem.base: REG = r12
                        operands[1].mem.disp: 0xff8
                operands[2].type: IMM = 0x0
                operands[3].type: IMM = 0x0
```

After:

```
% ./cstool/cstool -d --help ppc32beps 'f3ec0ff8'                                            
 0  f3 ec 0f f8  psq_st f31, -8(r12), 0, 0
        ID: 1694 (psq_st)
        op_count: 4
                operands[0].type: REG = f31
                operands[1].type: MEM
                        operands[1].mem.base: REG = r12
                        operands[1].mem.disp: 0xfffffff8
                operands[2].type: IMM = 0x0
                operands[3].type: IMM = 0x0
```

cc @kabeor

### CODE REVIEW

**Comment by kabeor** [comment]
plz add opcode test at https://github.com/capstone-engine/capstone/blob/next/suite/cstest/issues.cs

**Comment by kabeor** [comment]
Great! Merged.

**Comment by aquynh** [comment]
where is this fix from: by yourself, or from upstream llvm?

**Comment by terorie** [comment]
@aquynh Myself because LLVM doesn't support the paired-singles extension

**Pull request merged**
