### PR TITLE
Revert "x86: fix lcall seg:off format for x86-16 (#1827)"

### PR DESCRIPTION
**Pull request by trufae**
This reverts commit e4965783cfb30c12ae8f1b7bbce446fef03e2b68.

### CODE REVIEW

**Comment by trufae** [comment]
This commit was breaking all the x86 tests in r2 
Screenshot 2022-01-27 004219
Screenshot 2022-01-27 004401
Screenshot 2022-01-27 004447

**Comment by trufae** [comment]
The capstone CI should test for how the disassembly looks at least, that's a big regression

**Comment by aquynh** [comment]
yes we should add these test cases to https://github.com/capstone-engine/capstone/blob/next/suite/cstest/issues.cs

let me see how best to fix this, instead of reverting

**Comment by trufae** [comment]
I'll re-run the r2 ci after you.

**Comment by trufae** [comment]
Any estimation for the fix?

**Comment by aquynh** [comment]
lets merge this first then.

**Pull request merged**
